const APPOINTMENT_STATUS = {
  SCHEDULED: "SCHEDULED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW"
};

const APPOINTMENT_TYPES = {
  INITIAL: "INITIAL",
  FOLLOW_UP: "FOLLOW_UP",
  REVIEW: "REVIEW"
};

const REQUEST_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED"
};

module.exports = {
  APPOINTMENT_STATUS,
  APPOINTMENT_TYPES,
  REQUEST_STATUS
};
