const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  CONSULTANT: "CONSULTANT",
  PHYSIO: "PHYSIO",
  PHYSIOTHERAPIST: "PHYSIOTHERAPIST",
  NURSE: "NURSE",
  PATIENT: "PATIENT"
};

module.exports = ROLES;
